apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 10.21.1
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
