apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack-charts
  namespace: flux-system
spec:
  interval: 15m
  # Source: https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager
  url: https://charts.jetstack.io
