apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno-charts
  namespace: flux-system
spec:
  interval: 15m
  # Source: https://github.com/kyverno/kyverno/tree/main/charts/kyverno
  url: https://kyverno.github.io/kyverno/
